baseURL = "https://k1chn.com/"
languageCode = "en-us"
title = "K1CHN"

theme = 'purehugo'

[params]
githubName = "kitchen"
description = "putting the amateur in amateur radio"
hideSidebarIconText = true
