baseURL = "https://www.k1chn.com/"
languageCode = "en-us"
title = "K1CHN"

theme = 'pure-bootstrap'
# theme = 'purehugo'

[params]
githubName = "kitchen"
description = "amateurish amateur radio"
hideSidebarIconText = true
hideShareOptions = true
